### ISSUE TITLE
Nothing happen while taking attendance

### ISSUE THREAD

**Issue by shraoned** [venugopalkadamba/Face_Verification_based_Attendance_system#16]
Hello sir,
             Thank you for this awesome app & also learning resource. App is running successful, but while taking attendance camera is open & also id is displaying but nothing happening after that. I was add all the necessary fields & data in database like faculty, students, admin etc.

Please help me for this.

**Comment by venugopalkadamba** [comment]
Hello shraoned
After the Id is displayed the window will be shown until the user clicks the character S from keyboard. After that the database is updated for the people appeared in the camera.

**Comment by shraoned** [comment]
> Hello shraoned
> After the Id is displayed the window will be shown until the user clicks the character S from keyboard. After that the database is updated for the people appeared in the camera.

Okay...Work like charm.
Thank You So Much Sir...
