### ISSUE TITLE
i need help ,i don't know what the cause of the error 

### ISSUE THREAD

**Issue by bodyalrayes151999** [venugopalkadamba/Face_Verification_based_Attendance_system#17]
![image](https://user-images.githubusercontent.com/82846113/119862938-540a9780-bf19-11eb-8ffb-049930604bc5.png)

**Comment by venugopalkadamba** [comment]
Hi @bodyalrayes151999 
You need to login to the django admin panel and need to map the user to the faculty group.

**Comment by bodyalrayes151999** [comment]
> Hi @bodyalrayes151999
> You need to login to the django admin panel and need to map the user to the faculty group.

it pass the error and i just got another one 
![image](https://user-images.githubusercontent.com/82846113/120075577-20a74480-c0a2-11eb-8021-1568d82bbec2.png)

**Comment by bodyalrayes151999** [comment]
Thanks it work !!
