### ISSUE TITLE
While taking attendance it is not recognizing my face. And how can I cross check if my attendance is marked. Please help.

### ISSUE THREAD

**Issue by ayushyelne** [venugopalkadamba/Face_Verification_based_Attendance_system#30]

**Comment by venugopalkadamba** [comment]
You need to upload the images of the students from the add student section of the application and then take the attendance. When the attendance is taken by the application, the final attendance is shown as a table.

**Comment by ayushyelne** [comment]
It is giving me following error while taking attendance:
IndexError at /attendence/
