### ISSUE TITLE
how can I get the password of admin

### ISSUE THREAD

**Issue by Yabibal1624** [venugopalkadamba/Face_Verification_based_Attendance_system#33]
![image](https://user-images.githubusercontent.com/33721311/161587202-ec84c879-26e5-4705-8cf1-f492d8cd2bb1.png)

**Comment by venugopalkadamba** [comment]
You need to create a superuser using "python manage.py createsuperuser" command

**Comment by Yabibal1624** [comment]
I try to use this command but django.db.utils. operationalerror: database
is locked message. How can o solve this problem?

With best regards
