### ISSUE TITLE
Take attendance not working saying unknown

### ISSUE THREAD

**Issue by VishalDip** [venugopalkadamba/Face_Verification_based_Attendance_system#34]
Can you explain how to make take attendance work and what is admin panel username and password ?

**Comment by Proeditor07** [comment]
did you get the answer

**Comment by mraheelkhan** [comment]
@Proeditor07 You need to run  ```python manage.py createsuperuser``` command to create login.

**Comment by venugopalkadamba** [comment]
This command was updated in the readme a few days back, so closing this issue.
