### ISSUE TITLE
User has no faculty 

### ISSUE THREAD

**Issue by Sesuraja** [venugopalkadamba/Face_Verification_based_Attendance_system#39]
Related objects does not exist at/ attendance/
User has no faculty

**Comment by Mrship12138** [comment]
me too，how to solve this problem

**Comment by venugopalkadamba** [comment]
You'll need to assign the User to the faculty group in the Django admin
panel.

**Comment by Mrship12138** [comment]
thank you very much，i get it!



---- Replied Message ----
| From | Venu Gopal ***@***.***> |
| Date | 04/22/2023 13:38 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [venugopalkadamba/Face_Verification_based_Attendance_system] User has no faculty (Issue #39) |

You'll need to assign the User to the faculty group in the Django admin
panel.
