### ISSUE TITLE
How to run 

### ISSUE THREAD

**Issue by Praveen6399** [venugopalkadamba/Face_Verification_based_Attendance_system#41]
How to run this project Its coming so much of error for me

**Comment by mahimairaja** [comment]
Can you please specify the error or provide a screenshot?

**Comment by DD45970** [comment]
how to run this project please share video if possible

**Comment by mahimairaja** [comment]
@DD45970  Have you tried to execute according to the instructions given in the repo? If you find any difficulties please let me know

**Comment by Praveen6399** [comment]
Thanks for asking me sir I have finished my final year project and I am
search for job

**Comment by mahimairaja** [comment]
Connect with me through linkedin @Praveen6399
