### ISSUE TITLE
What to write in login page. What is password and id??

### ISSUE THREAD

**Issue by Shwetank2101** [venugopalkadamba/Face_Verification_based_Attendance_system#6]
![image](https://user-images.githubusercontent.com/60538633/103877687-6bc4b900-50fb-11eb-8f95-cdfff954d0b9.png)

**Comment by venugopalkadamba** [comment]
Hi Shwetank, You need to first create a superuser by running the following command "python manage.py createsuperuser" and then login with those credentials through login page.

**Comment by Shwetank2101** [comment]
Oka thank you . It worked
