### ISSUE TITLE
RelatedObjectDoesNotExist at /account/

### ISSUE THREAD

**Issue by AmbiTyga** [venugopalkadamba/Face_Verification_based_Attendance_system#7]
I think there is some problem
![image](https://user-images.githubusercontent.com/39136064/105632171-d43fc400-5e77-11eb-8425-89b2d5a0c40e.png)
I have no idea about this

**Comment by venugopalkadamba** [comment]
You need to open the django admin panel and then assign the registered user to faculty group.
